print("Hello from Abhishek")
print('Hello from Abid')
print("Hello Srishti Vishnoi this side")
print("Hello From Mohammad Imteyaz")
print("Hello From subham mishra")
print("Hello from Varun Khatana")
print("Hello from SUVRAT AGNIHOTRI")
print("Hello from Suryansh Mathur")
print("Hello from Ria")
print("Hello from Shristy Pandey")
print("Hello from Ayushi Srivastava")
print("Hello everyone, from Vivek Kumar Maurya")
print("Hello from Jayesh Bhushan")
